// Generated by Copilot
"use server";

import { prisma } from "@/lib/prisma";

import { OrderStatus } from "@/generated/prisma/enums";

export type DashboardStats = {
  total_templates: number;
  total_orders: number;
  total_categories: number;
  active_templates: number;
  pending_orders: number;
  completed_orders: number;
};

/**
 * Get dashboard statistics
 * Returns aggregated data for dashboard overview
 */
export async function getDashboardStats(): Promise<DashboardStats> {
  try {
    const [
      total_templates,
      total_orders,
      total_categories,
      active_templates,
      pending_orders,
      completed_orders,
    ] = await Promise.all([
      prisma.template.count(),
      prisma.order.count(),
      prisma.category.count(),
      prisma.template.count({ where: { is_active: true } }),
      prisma.order.count({ where: { status: OrderStatus.PENDING } }),
      prisma.order.count({ where: { status: OrderStatus.COMPLETED } }),
    ]);

    return {
      total_templates,
      total_orders,
      total_categories,
      active_templates,
      pending_orders,
      completed_orders,
    };
  } catch (error) {
    console.error("Error fetching dashboard stats:", error);
    throw new Error("Gagal mengambil statistik dashboard");
  }
}
