import "dotenv/config";

import { prisma } from "@/lib/prisma";

async function main() {
  console.log("🌱 Starting database seed...");

  // Create Categories
  console.log("📂 Creating categories...");
  const categories = await Promise.all([
    prisma.category.create({
      data: {
        name: "Wedding Invitation",
        description: "Template undangan pernikahan modern dan elegan",
        slug: "wedding-invitation",
        image:
          "https://placehold.co/400x300/blue/white.png?text=Wedding+Invitation",
        is_active: true,
      },
    }),
    prisma.category.create({
      data: {
        name: "Birthday Invitation",
        description: "Template undangan ulang tahun yang meriah",
        slug: "birthday-invitation",
        image:
          "https://placehold.co/400x300/blue/white.png?text=Birthday+Invitation",
        is_active: true,
      },
    }),
    prisma.category.create({
      data: {
        name: "Corporate Event",
        description: "Template undangan acara perusahaan dan bisnis",
        slug: "corporate-event",
        image:
          "https://placehold.co/400x300/blue/white.png?text=Corporate+Event",
        is_active: true,
      },
    }),
    prisma.category.create({
      data: {
        name: "Graduation",
        description: "Template undangan wisuda dan kelulusan",
        slug: "graduation",
        image: "https://placehold.co/400x300/blue/white.png?text=Graduation",
        is_active: true,
      },
    }),
    prisma.category.create({
      data: {
        name: "Baby Shower",
        description: "Template undangan baby shower dan kelahiran",
        slug: "baby-shower",
        image: "https://placehold.co/400x300/blue/white.png?text=Baby+Shower",
        is_active: true,
      },
    }),
  ]);

  console.log(`✅ Created ${categories.length} categories`);

  // Create Templates
  // Generated by Copilot
  console.log("🎨 Creating templates...");
  const templates = [
    // Wedding Templates
    {
      title: "Elegant Rose Wedding",
      description:
        "Template undangan pernikahan dengan tema mawar yang elegan dan romantis",
      price: 150000,
      discount_price: 120000,
      image: "https://placehold.co/600x600/ff69b4/white.png?text=Elegant+Rose",
      thumbnail:
        "https://placehold.co/400x400/ff69b4/white.png?text=Elegant+Rose",
      preview_images: [
        "https://placehold.co/900x1600/ff69b4/white.png?text=Preview+1",
        "https://placehold.co/900x1600/ffb6c1/white.png?text=Preview+2",
        "https://placehold.co/900x1600/ffc0cb/white.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/elegantrose",
      demo_url: "https://demo.sasak-invite.com/elegant-rose",
      category_id: categories[0].id,
      is_active: true,
      is_featured: true,
      tags: ["wedding", "elegant", "rose", "romantic", "pink"],
    },
    {
      title: "Modern Minimalist Wedding",
      description:
        "Template undangan pernikahan dengan desain minimalis dan modern",
      price: 200000,
      image: "https://placehold.co/600x600/e8e8e8/333.png?text=Modern+Minimal",
      thumbnail:
        "https://placehold.co/400x400/e8e8e8/333.png?text=Modern+Minimal",
      preview_images: [
        "https://placehold.co/900x1600/f5f5f5/333.png?text=Preview+1",
        "https://placehold.co/900x1600/e8e8e8/333.png?text=Preview+2",
        "https://placehold.co/900x1600/ffffff/333.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/modernminimal",
      demo_url: "https://demo.sasak-invite.com/modern-minimal",
      category_id: categories[0].id,
      is_active: true,
      is_featured: false,
      tags: ["wedding", "minimal", "modern", "clean", "white"],
    },
    {
      title: "Traditional Javanese Wedding",
      description:
        "Template undangan pernikahan dengan nuansa adat Jawa yang tradisional",
      price: 175000,
      discount_price: 150000,
      image: "https://placehold.co/600x600/8b4513/white.png?text=Javanese",
      thumbnail: "https://placehold.co/400x400/8b4513/white.png?text=Javanese",
      preview_images: [
        "https://placehold.co/900x1600/8b4513/white.png?text=Preview+1",
        "https://placehold.co/900x1600/a0522d/white.png?text=Preview+2",
        "https://placehold.co/900x1600/cd853f/white.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/traditionaljavanese",
      demo_url: "https://demo.sasak-invite.com/traditional-javanese",
      category_id: categories[0].id,
      is_active: true,
      is_featured: true,
      tags: ["wedding", "traditional", "javanese", "cultural", "brown"],
    },
    {
      title: "Garden Wedding Paradise",
      description:
        "Template undangan pernikahan dengan tema taman yang segar dan natural",
      price: 180000,
      discount_price: 160000,
      image: "https://placehold.co/600x600/90ee90/333.png?text=Garden+Wedding",
      thumbnail:
        "https://placehold.co/400x400/90ee90/333.png?text=Garden+Wedding",
      preview_images: [
        "https://placehold.co/900x1600/90ee90/333.png?text=Preview+1",
        "https://placehold.co/900x1600/98fb98/333.png?text=Preview+2",
        "https://placehold.co/900x1600/7cfc00/333.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/gardenwedding",
      demo_url: "https://demo.sasak-invite.com/garden-wedding",
      category_id: categories[0].id,
      is_active: true,
      is_featured: true,
      tags: ["wedding", "garden", "natural", "green", "outdoor"],
    },
    // Birthday Templates
    {
      title: "Kids Birthday Party",
      description:
        "Template undangan ulang tahun anak dengan tema kartun yang ceria",
      price: 75000,
      discount_price: 60000,
      image: "https://placehold.co/600x600/ffa500/white.png?text=Kids+Party",
      thumbnail:
        "https://placehold.co/400x400/ffa500/white.png?text=Kids+Party",
      preview_images: [
        "https://placehold.co/900x1600/ffa500/white.png?text=Preview+1",
        "https://placehold.co/900x1600/ff8c00/white.png?text=Preview+2",
        "https://placehold.co/900x1600/ffd700/333.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/kidsbirthdayparty",
      demo_url: "https://demo.sasak-invite.com/kids-birthday",
      category_id: categories[1].id,
      is_active: true,
      is_featured: true,
      tags: ["birthday", "kids", "cartoon", "colorful", "fun"],
    },
    {
      title: "Adult Birthday Celebration",
      description:
        "Template undangan ulang tahun dewasa dengan desain yang sophisticated",
      price: 100000,
      image:
        "https://placehold.co/600x600/4169e1/white.png?text=Adult+Birthday",
      thumbnail:
        "https://placehold.co/400x400/4169e1/white.png?text=Adult+Birthday",
      preview_images: [
        "https://placehold.co/900x1600/4169e1/white.png?text=Preview+1",
        "https://placehold.co/900x1600/4682b4/white.png?text=Preview+2",
        "https://placehold.co/900x1600/5f9ea0/white.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/adultbirthday",
      demo_url: "https://demo.sasak-invite.com/adult-birthday",
      category_id: categories[1].id,
      is_active: true,
      is_featured: false,
      tags: ["birthday", "adult", "sophisticated", "party", "celebration"],
    },
    {
      title: "Sweet Sixteen Birthday",
      description: "Template undangan ulang tahun sweet seventeen yang glamour",
      price: 95000,
      image: "https://placehold.co/600x600/ff1493/white.png?text=Sweet+16",
      thumbnail: "https://placehold.co/400x400/ff1493/white.png?text=Sweet+16",
      preview_images: [
        "https://placehold.co/900x1600/ff1493/white.png?text=Preview+1",
        "https://placehold.co/900x1600/ff69b4/white.png?text=Preview+2",
        "https://placehold.co/900x1600/db7093/white.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/sweetsixtenn",
      demo_url: "https://demo.sasak-invite.com/sweet-sixteen",
      category_id: categories[1].id,
      is_active: true,
      is_featured: true,
      tags: ["birthday", "sweet16", "glamour", "teenager", "party"],
    },
    // Corporate Templates
    {
      title: "Business Conference",
      description: "Template undangan konferensi bisnis yang profesional",
      price: 125000,
      image: "https://placehold.co/600x600/1e3a8a/white.png?text=Conference",
      thumbnail:
        "https://placehold.co/400x400/1e3a8a/white.png?text=Conference",
      preview_images: [
        "https://placehold.co/900x1600/1e3a8a/white.png?text=Preview+1",
        "https://placehold.co/900x1600/1e40af/white.png?text=Preview+2",
        "https://placehold.co/900x1600/1d4ed8/white.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/businessconference",
      demo_url: "https://demo.sasak-invite.com/business-conference",
      category_id: categories[2].id,
      is_active: true,
      is_featured: false,
      tags: ["corporate", "business", "conference", "professional", "blue"],
    },
    {
      title: "Company Anniversary",
      description: "Template undangan HUT perusahaan yang formal dan mewah",
      price: 150000,
      image: "https://placehold.co/600x600/b8860b/white.png?text=Anniversary",
      thumbnail:
        "https://placehold.co/400x400/b8860b/white.png?text=Anniversary",
      preview_images: [
        "https://placehold.co/900x1600/b8860b/white.png?text=Preview+1",
        "https://placehold.co/900x1600/daa520/333.png?text=Preview+2",
        "https://placehold.co/900x1600/ffd700/333.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/companyanniversary",
      demo_url: "https://demo.sasak-invite.com/company-anniversary",
      category_id: categories[2].id,
      is_active: true,
      is_featured: true,
      tags: ["corporate", "anniversary", "formal", "luxury", "gold"],
    },
    // Graduation Templates
    {
      title: "University Graduation",
      description: "Template undangan wisuda universitas yang elegan",
      price: 90000,
      image: "https://placehold.co/600x600/2563eb/white.png?text=Graduation",
      thumbnail:
        "https://placehold.co/400x400/2563eb/white.png?text=Graduation",
      preview_images: [
        "https://placehold.co/900x1600/2563eb/white.png?text=Preview+1",
        "https://placehold.co/900x1600/1d4ed8/white.png?text=Preview+2",
        "https://placehold.co/900x1600/3b82f6/white.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/universitygraduation",
      demo_url: "https://demo.sasak-invite.com/university-graduation",
      category_id: categories[3].id,
      is_active: true,
      is_featured: false,
      tags: ["graduation", "university", "academic", "achievement", "blue"],
    },
    // Baby Shower Templates
    {
      title: "Sweet Baby Shower",
      description:
        "Template undangan baby shower dengan tema yang manis dan lembut",
      price: 80000,
      discount_price: 65000,
      image: "https://placehold.co/600x600/ffc0cb/333.png?text=Baby+Shower",
      thumbnail: "https://placehold.co/400x400/ffc0cb/333.png?text=Baby+Shower",
      preview_images: [
        "https://placehold.co/900x1600/ffc0cb/333.png?text=Preview+1",
        "https://placehold.co/900x1600/ffb6c1/333.png?text=Preview+2",
        "https://placehold.co/900x1600/ffe4e1/333.png?text=Preview+3",
      ],
      lynk_id_url: "https://lynk.id/sweetbabyshower",
      demo_url: "https://demo.sasak-invite.com/sweet-baby-shower",
      category_id: categories[4].id,
      is_active: true,
      is_featured: true,
      tags: ["baby-shower", "sweet", "soft", "pastel", "cute"],
    },
  ];

  for (const template of templates) {
    await prisma.template.create({ data: template });
  }

  console.log(`✅ Created ${templates.length} templates`);

  // Create Sample Orders
  // Generated by Copilot
  console.log("📋 Creating sample orders...");
  const orders = [
    {
      order_number: "INV-001",
      customer_name: "Ahmad Zulkarnain",
      customer_email: "ahmad.zul@email.com",
      customer_phone: "+6281234567890",
      total_amount: 120000,
      status: "COMPLETED",
      payment_method: "Transfer Bank",
      lynk_id_transaction_id: "LYN-TRX-001",
      notes: "Template sudah dikirim via email",
    },
    {
      order_number: "INV-002",
      customer_name: "Siti Nurhaliza",
      customer_email: "siti.nur@email.com",
      customer_phone: "+6281987654321",
      total_amount: 60000,
      status: "PAID",
      payment_method: "E-Wallet",
      lynk_id_transaction_id: "LYN-TRX-002",
      notes: "Menunggu proses download link",
    },
    {
      order_number: "INV-003",
      customer_name: "Budi Santoso",
      customer_email: "budi.santoso@email.com",
      customer_phone: "+6281122334455",
      total_amount: 150000,
      status: "PROCESSING",
      payment_method: "Transfer Bank",
      lynk_id_transaction_id: "LYN-TRX-003",
      notes: "Sedang proses customization",
    },
    {
      order_number: "INV-004",
      customer_name: "Dewi Lestari",
      customer_email: "dewi.lestari@email.com",
      customer_phone: "+6281345678901",
      total_amount: 200000,
      status: "COMPLETED",
      payment_method: "Credit Card",
      lynk_id_transaction_id: "LYN-TRX-004",
      notes: "Pelanggan sangat puas dengan hasilnya",
    },
    {
      order_number: "INV-005",
      customer_name: "Rizki Ramadhan",
      customer_email: "rizki.ram@email.com",
      customer_phone: "+6281456789012",
      total_amount: 180000,
      status: "PAID",
      payment_method: "Transfer Bank",
      lynk_id_transaction_id: "LYN-TRX-005",
      notes: "Siap untuk diproses",
    },
    {
      order_number: "INV-006",
      customer_name: "Linda Kusuma",
      customer_email: "linda.kusuma@email.com",
      customer_phone: "+6281567890123",
      total_amount: 75000,
      status: "COMPLETED",
      payment_method: "E-Wallet",
      lynk_id_transaction_id: "LYN-TRX-006",
      notes: "Template undangan anak",
    },
    {
      order_number: "INV-007",
      customer_name: "Andi Prasetyo",
      customer_email: "andi.prasetyo@email.com",
      customer_phone: "+6281678901234",
      total_amount: 100000,
      status: "PROCESSING",
      payment_method: "Transfer Bank",
      lynk_id_transaction_id: "LYN-TRX-007",
      notes: "Revisi pertama",
    },
    {
      order_number: "INV-008",
      customer_name: "Maya Sari",
      customer_email: "maya.sari@email.com",
      customer_phone: "+6281789012345",
      total_amount: 125000,
      status: "COMPLETED",
      payment_method: "E-Wallet",
      lynk_id_transaction_id: "LYN-TRX-008",
      notes: "Untuk acara konferensi perusahaan",
    },
    {
      order_number: "INV-009",
      customer_name: "Hendra Wijaya",
      customer_email: "hendra.wijaya@email.com",
      customer_phone: "+6281890123456",
      total_amount: 150000,
      status: "PAID",
      payment_method: "Credit Card",
      lynk_id_transaction_id: "LYN-TRX-009",
      notes: "HUT perusahaan ke-10",
    },
    {
      order_number: "INV-010",
      customer_name: "Putri Amelia",
      customer_email: "putri.amelia@email.com",
      customer_phone: "+6281901234567",
      total_amount: 90000,
      status: "COMPLETED",
      payment_method: "Transfer Bank",
      lynk_id_transaction_id: "LYN-TRX-010",
      notes: "Undangan wisuda",
    },
    {
      order_number: "INV-011",
      customer_name: "Fajar Nugroho",
      customer_email: "fajar.nugroho@email.com",
      customer_phone: "+6281012345678",
      total_amount: 80000,
      status: "PROCESSING",
      payment_method: "E-Wallet",
      lynk_id_transaction_id: "LYN-TRX-011",
      notes: "Baby shower untuk anak pertama",
    },
  ];

  // Note: Simplified order creation since we need to create templates first
  // Generated by Copilot
  const createdTemplates = await prisma.template.findMany();

  for (let i = 0; i < orders.length; i++) {
    const order = orders[i];
    const templateIndex = i % createdTemplates.length;
    await prisma.order.create({
      data: {
        order_number: order.order_number,
        customer_name: order.customer_name,
        customer_email: order.customer_email,
        customer_phone: order.customer_phone,
        total_amount: order.total_amount,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        status: order.status as any,
        payment_method: order.payment_method,
        lynk_id_transaction_id: order.lynk_id_transaction_id,
        notes: order.notes,
        order_items: {
          create: [
            {
              template_id: createdTemplates[templateIndex].id,
              price: order.total_amount,
              quantity: 1,
            },
          ],
        },
      },
    });
  }

  console.log(`✅ Created ${orders.length} sample orders`);

  console.log("🎉 Database seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Error during database seed:");
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
