// Generated by Copilot
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import type { DashboardStats } from "@/actions/dashboard-action";
import { DASHBOARD_STATS_CONFIG } from "@/constants/dashboardData";

type DashboardStatsProps = {
  stats: DashboardStats;
};

export const DashboardStatsSection = ({ stats }: DashboardStatsProps) => {
  return (
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      {DASHBOARD_STATS_CONFIG.map((config) => (
        <Card key={config.title} className="gap-2">
          <CardHeader className="flex flex-row items-center justify-between space-y-0">
            <CardTitle className="text-sm font-medium">
              {config.title}
            </CardTitle>

            <div className={`rounded-lg p-2 ${config.bgColor}`}>
              <config.icon className={`h-4 w-4 ${config.color}`} />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {config.getValueKey(stats)}
            </div>
            <CardDescription>{config.getTrend(stats)}</CardDescription>
          </CardContent>
        </Card>
      ))}
    </div>
  );
};
